### ISSUE TITLE
nightly on windows (2.11.x/jdk6)

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#36] opened 2015-02-23 22:42 UTC
- [ ] install curl (need to update cygwin base image :-(() on jenkins-worker-windows-publish (done manually for now)
- [ ] install /usr/local/share/jvm/jvm-select script on jenkins-worker-windows-publish (worked around for 2.11.x; fix needed to add 2.12.x support)
- [ ] install ant on jenkins-worker-windows-publish (just unzip the archive and set ANT_HOME and PATH accordingly in windows node env vars) (done manually for now)
- [X] get pull-binary-libs craziness to work on cygwin (ARGH)

**Comment by SethTisue** [comment] 2015-09-04 16:55
I don't know what "pull-binary-libs craziness" is, but fwiw, in my local Cygwin setup, running `sh pull-binary-libs.sh` separately, before running ant, worked fine

**Comment by adriaanm** [comment] 2015-09-04 17:28
Yeah, it works on some cygwin setups, but not scala-ci's... The craziness is exactly what you would think. Those scripts... Cygwin.... :anger:

**Comment by SethTisue** [comment] 2015-09-10 19:10
if we can use the sbt build instead, then we won't need ant (or curl?).

we know that jenkins-worker-windows-publish already has a working sbt install, since that's what e.g. release/website/update-api uses

**Comment by SethTisue** [comment] 2015-09-14 23:20
it might be helpful to look at how this was done in on the old Jenkins infrastructure. "The config is stored at https://github.com/scala/jenkins-config and the scripts in https://github.com/scala/jenkins-scripts" says Adriaan.

I might also want to look at the Jenkins job configs on https://scala-webapps.epfl.ch/jenkins/; I wrote Fabien Salvi just now to ask for access. (Jenkins won't even let you see job configs without a login.)

EDIT:
- old script is https://github.com/scala/jenkins-scripts/blob/master/job/scala-nightly-windows
- old config is https://github.com/scala/jenkins-config/blob/master/jobs/scala-nightly-windows-2.11.x/config.xml

**Comment by SethTisue** [comment] 2015-09-17 22:51
the use-the-sbt-build-it'll-be-easier idea turned out to be not so hot. ant has to (for now) be manually installed, but then it just works. with sbt, you can run the junit tests and scalacheck tests but the other pertest tests don't work. the problem is surely fixable, and I expect we'll fix it eventually, but it isn't really worth tackling until we have the ability to run individual partest tests through sbt (https://github.com/scala/scala-partest/pull/24, https://github.com/scala/scala-partest-interface/pull/5), since otherwise if something fails there is no way to interactively test your fix (`test/partest.bat` doesn't seem to work at present, and we could fix that too or instead, but I think it's ultimately better to put the energy into sbt-based things).

I did determine that when the sbt build tries to run a shell script (such as `pull-binary-libs.sh`), it needs to do it with e.g. `Seq("bash", "myscript.sh").!` rather than just `"myscript.sh".!`. So, noting that for future reference:

``` diff
-    testOptions in IntegrationTest += Tests.Setup( () => root.base.getAbsolutePath + "/pull-binary-libs.sh" ! ),
+    testOptions in IntegrationTest += Tests.Setup( () => Seq("bash", root.base.getAbsolutePath + "pull-binary-libs.sh") ! ),
```

**Comment by SethTisue** [comment] 2015-09-17 22:57
> Yeah, it works on some cygwin setups, but not scala-ci's

Not sure what error message you were getting, but if it was `'\r': command not found`, that's just because `pull-binary-libs.sh` was being checked out of version control with Windows line endings. It's possible to make the script work with `export SHELLOPTS; set -o igncr` but it's better to just do the checkout with LF not CRLF.

We intend to make `eol=lf` the default windows checkout (see https://issues.scala-lang.org/browse/SI-9472), but if that ends up not happening (or just hasn't happened yet), we'll need to pay attention to this in the config for the Jenkins job.

**Comment by SethTisue** [comment] 2015-09-17 23:00
> [old] Jenkins won't even let you see job configs without a login

Adriaan points out that the old Jenkins XML configs are in https://github.com/scala/jenkins-config (private repo), and the scripts are in https://github.com/scala/jenkins-scripts, so admin access to old Jenkins may not actually be useful, but in any case I have it now and my next PR with a round of doc improvements will include instructions for getting it.

**Comment by SethTisue** [comment] 2015-09-17 23:07
notes on my manual testing process, to help me pick it up later. I:
- untarred an Ant distribution into `/home/tisue/apache-ant-1.9.6`
- `git clone`d the Scala repo into `/home/tisue/scala`
- inside the `scala` dir, added `* text eol=lf` to `.gitattributes` and followed the "Refreshing a repository after changing line endings" instructions at https://help.github.com/articles/dealing-with-line-endings/#platform-windows) to get rid of the CR characters in the working copies
- to start ant, used `ANT_OPTS="-Dfile.encoding=UTF-8 -server -XX:+AggressiveOpts -XX:+UseParNewGC -Xmx2G -Xss1M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=128M" ../apache-ant-1.9.6/bin/ant.bat -Dstarr.version=2.11.7 -Dscalac.args.optimise=-optimise -Dlocker.skip=1 test`
- to start sbt (but see above remarks about ant being preferable for now), used `java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -jar C:\sbt/sbt-launch.jar <cmd>` (interactive sbt use didn't work because of terminal problems, so I just specify the command I want on the command line each time

EDIT: from a fresh checkout, you might need to have `set -o igncr` for some steps, and need _not_ to have it for other steps? not totally sure, but if something gets stuck with weird errors (that perhaps even mention `\r`), it's worth flipping that switch and trying again.

**Comment by SethTisue** [comment] 2015-09-17 23:08
I'll want to keep an eye out for possible failures related to https://github.com/scala/scala/pull/4727 which unset the execute bits on the number of files. a previous similar PR ended up partially reverted for causing test failures on Windows, but @lrytz doesn't remember the details of why. 4727 was merged anyway, so just something to be aware of if failures crop up.

EDIT (Sep 25): this hasn't cropped up.

**Comment by SethTisue** [comment] 2015-09-17 23:13
running with ant and with git `cr=lf` all junit tests pass, but there some partest failures I have not investigated yet. full log at https://gist.github.com/SethTisue/c9551a4988a78c9c969d. the particular failures are:

``` text
test/partest test/files/pos/t9370
test/partest test/files/run/inline-ex-handlers.scala
test/partest test/files/run/test-cpp.scala
```

EDIT: fixed in https://github.com/scala/scala/pull/4770

**Comment by adriaanm** [comment] 2015-09-18 07:59
Cool, great progress! Thanks for taking on the windows boss level! I do think we run our scala-ci cygwin under igncr already:

```
➜  scala-jenkins-infra git:(master) g --no-pager grep igncr
attributes/worker.rb:75:        "SHELLOPTS"     => "igncr" # ignore line-ending issues in shell scripts
recipes/_worker-config-windows-cygwin.rb:55:  environment ({'SHELLOPTS' => 'igncr'})
recipes/_worker-config-windows-cygwin.rb:63:  environment ({'SHELLOPTS' => 'igncr'})
recipes/_worker-config-windows-cygwin.rb:75:  environment ({'SHELLOPTS' => 'igncr'})
```

**Comment by adriaanm** [comment] 2015-09-18 07:59
I'm afraid I don't remember the other issues I had, but if they can't be reproduced, I'll chalk it up as a win :-)

**Comment by adriaanm** [comment] 2015-09-20 13:30
Cross refs: https://github.com/scala/scala/pull/4750, https://github.com/scala/scala/pull/4755, https://github.com/scala/scala/pull/4744, https://github.com/scala/scala-jenkins-infra/pull/128

**Comment by SethTisue** [comment] 2015-09-28 01:26
primitive initial stab, just to get the ball rolling: https://github.com/SethTisue/scala-jenkins-infra/commits/wip/windows-test, https://github.com/SethTisue/scala/tree/seth-wip/windows-integrate, https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-windows/3/

**Comment by SethTisue** [comment] 2015-09-29 21:38
I've been plagued by having `git clean -fdx` fail with exit status 1, forcing me to manually ssh in to cygwin and `rm -rf workspace/scala-2.11.x-integrate-windows` to start over with a clean checkout. The failure to clean is reproducible from the cygwin command line, but git 1.9.5 was not printing any diagnostics and doesn't have a `--verbose` or `--debug` option. one possible clue: `git clean -fx` would succeed, the `-d` is needed to fail.

1.9.5 is a pretty old version so I hoped upgrading Git might help. And indeed there seem to now be better diagnostics:

```
$ git clean -fdx && echo done
Unlink of file 'lib/ant/ant-contrib.jar' failed. Should I try again? (y/n) y
Unlink of file 'lib/ant/ant-contrib.jar' failed. Should I try again? (y/n) y
Unlink of file 'lib/ant/ant-contrib.jar' failed. Should I try again? (y/n) y
Unlink of file 'lib/ant/ant-contrib.jar' failed. Should I try again? (y/n) n
warning: failed to remove lib/ant/ant-contrib.jar
Unlink of file 'lib/ant/maven-ant-tasks-2.1.1.jar' failed. Should I try again? (y/n) n
warning: failed to remove lib/ant/maven-ant-tasks-2.1.1.jar

jenkins@WIN-B3L3RGFIR9T ~/workspace/scala-2.11.x-integrate-windows
$ git clean -fdx && echo done
Removing lib/ant/ant-contrib.jar
Removing lib/ant/maven-ant-tasks-2.1.1.jar
done
```

looks like it might be files left open, somehow, from the previous run. in this example the problem went away on a second try. I started the second build very quickly after aborting a previous one, so perhaps this won't occur again in practice.

EDIT: Totally guessed wrong here, the unlink-failed thing was a one-time failure, and the Git version upgrade did nothing to improve the `git clean` situation. What did improve the `git clean` situation was `git config core.longpaths true` — it was having trouble deleting the `build` directory where some .class files in deeply nested directories also had very long names.

**Comment by SethTisue** [comment] 2015-10-08 16:30
a chunk of progress on this is at https://github.com/scala/scala-jenkins-infra/pull/132

EDIT: and another chunk at https://github.com/scala/scala/pull/4795

**Comment by SethTisue** [comment] 2015-10-08 17:56
I am reeeeeeeeeally tempted to recommend we just stick with manually installed Git, manually installed curl, manually installed Ant, and a couple of manually installed JDK's, rather than spend 10x as much time trying to make Chef do it.

**Comment by lrytz** [comment] 2015-10-08 18:00
There's also https://chocolatey.org which I think works pretty well

**Comment by SethTisue** [comment] 2015-11-06 22:02
another increment of progress, this will now run nightly: https://github.com/scala/scala-jenkins-infra/pull/140

**Comment by SethTisue** [comment] 2015-11-06 23:54
calling this done now that we have separate tickets for #142 (which I plan to tackle) and #141 (which I don't)

**Closed as completed by SethTisue** 2015-11-06 23:54 UTC
Labels: enhancement

**Comment by adriaanm** [comment] 2016-04-21 21:28
btw, windows now has java 8 installed on it -- i may have broken this, but jenkins wasn't able to bring up the windows worker at all without upgrading java

**Comment by adriaanm** [comment] 2016-04-22 03:37
it's probably enough to switch JAVA_HOME (and, correspondingly, PATH by adding `/bin`) between `c:/Program Files/Java/jdk1.8.0_92/` and  `C:/java/jdk-1.6`
